Repository DSM-SSGP/SSGP-iOS, pull requests merged in 2021-09, with the labels that each got.

#43 🔀 :: (#42) MapView와 ViewModel 바인딩
  Sources/Extension/CLLocationManager.swift
  Sources/View/Map/MapViewController.swift
  Sources/ViewModel/Map/MapViewModel.swift
Labels: Chore

#46 🔀 :: (#45) 로그인 페이지 이동 함수 구현
  Sources/Extension/ViewController.swift
Labels: 기능 추가

#48 🔀 :: (#36) MyPage UI 구현
  Resources/Assets.xcassets/Color/MyPage.colorset/Contents.json
  Resources/Assets.xcassets/Color/MyPageMenu.colorset/Contents.json
  Resources/Assets.xcassets/Image/MypageMenuLogo/Contents.json
  Resources/Assets.xcassets/Image/ProfileImage.imageset/2.png
  Resources/Assets.xcassets/Image/ProfileImage.imageset/3.png
  Resources/Assets.xcassets/Image/ProfileImage.imageset/Contents.json
  Resources/Assets.xcassets/Image/ProfileImage.imageset/Group 107.png
  Sources/View/MyPage/MyPageMenuTableViewCell.swift
  Sources/View/MyPage/MyPageViewController.swift
Labels: 기능 추가

#50 🔀 :: (#49) Rx 관련 모듈들 버전업
  Podfile
  Podfile.lock
Labels: 프로젝트 설정
