Repository DSM-SSGP/SSGP-iOS, pull requests merged in 2021-08, with the labels that each got.

#18 🔀 :: (#16, #17) 아이콘 및 Display Name 세팅
  Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  Supporting Files/Info.plist
Labels: 프로젝트 설정

#20 🔀 :: (#19) 이넘 네이밍 변경 및 관련 코드 수정
  Sources/Model/Brand.swift
  Sources/View/Reuseable/ProductTableViewCell.swift
Labels: 리펙토링

#25 🔀 :: (#24) 이미지 세팅 및 디렉터리 정리
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/cuANT.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/cuANT.imageset/cuANT-2.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/cuANT.imageset/cuANT-3.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/cuANT.imageset/cuANT.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/emart24ANT.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/emart24ANT.imageset/emartANT-2.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/emart24ANT.imageset/emartANT-3.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/emart24ANT.imageset/emartANT.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/gs25ANT.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/gs25ANT.imageset/gs25ANT-2.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/gs25ANT.imageset/gs25ANT-3.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/gs25ANT.imageset/gs25ANT.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/ministopANT.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/ministopANT.imageset/ministopANT-2.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/ministopANT.imageset/ministopANT-3.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/ministopANT.imageset/ministopANT.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/sevenelevenANT.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/sevenelevenANT.imageset/Group 105-2.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/sevenelevenANT.imageset/Group 105-3.png
  Resources/Assets.xcassets/Image/StoreLogo/Annotation Image/sevenelevenANT.imageset/Group 105.png
  Resources/Assets.xcassets/Image/StoreLogo/CU.imageset/220px-CU_BI_(2017) 1-2.png
  Resources/Assets.xcassets/Image/StoreLogo/CU.imageset/220px-CU_BI_(2017) 1-3.png
  Resources/Assets.xcassets/Image/StoreLogo/CU.imageset/220px-CU_BI_(2017) 1.png
  Resources/Assets.xcassets/Image/StoreLogo/CU.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/EMART24.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/EMART24.imageset/emart24-1.png
  Resources/Assets.xcassets/Image/StoreLogo/EMART24.imageset/emart24-2.png
  Resources/Assets.xcassets/Image/StoreLogo/EMART24.imageset/emart24-3.png
  Resources/Assets.xcassets/Image/StoreLogo/GS25.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/GS25.imageset/R800x0 2-2.png
  Resources/Assets.xcassets/Image/StoreLogo/GS25.imageset/R800x0 2-3.png
  Resources/Assets.xcassets/Image/StoreLogo/GS25.imageset/R800x0 2.png
  Resources/Assets.xcassets/Image/StoreLogo/MINISTOP.imageset/1200px-MINISTOP_logo 1-2.png
  Resources/Assets.xcassets/Image/StoreLogo/MINISTOP.imageset/1200px-MINISTOP_logo 1-3.png
  Resources/Assets.xcassets/Image/StoreLogo/MINISTOP.imageset/1200px-MINISTOP_logo 1.png
  Resources/Assets.xcassets/Image/StoreLogo/MINISTOP.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreLogo/SEVENELEVEN.imageset/1055px-7-eleven_logo 1-2.png
  Resources/Assets.xcassets/Image/StoreLogo/SEVENELEVEN.imageset/1055px-7-eleven_logo 1-3.png
  Resources/Assets.xcassets/Image/StoreLogo/SEVENELEVEN.imageset/1055px-7-eleven_logo 1.png
  Resources/Assets.xcassets/Image/StoreLogo/SEVENELEVEN.imageset/Contents.json
Labels: Chore

#29 🔀 :: (#21) 로그인 페이지 UI 구현
  Project.swift
  Resources/Assets.xcassets/Image/LoginPageImage.imageset/Contents.json
  Resources/Assets.xcassets/Image/LoginPageImage.imageset/loginPageImage.png
  Resources/Assets.xcassets/Image/LoginPageImage.imageset/loginPageImage2.png
  Resources/Assets.xcassets/Image/LoginPageImage.imageset/loginPageImage3.png
  Resources/Assets.xcassets/Image/StoreIcon.imageset/Contents.json
  Resources/Assets.xcassets/Image/StoreIcon.imageset/StoreIcon.png
  Resources/Assets.xcassets/Image/StoreIcon.imageset/StoreIcon2.png
  Resources/Assets.xcassets/Image/StoreIcon.imageset/StoreIcon3.png
  Resources/pulse.json
  Sources/View/Auth/LoginViewController.swift
  Supporting Files/SSGP.entitlements
Labels: 기능 추가

#31 🔀 :: (#30) ProductTableViewCell 수정 완료
  Sources/View/Reuseable/ProductTableViewCell.swift
Labels: Chore

#32 🔀 :: (#27) 알림 셀 개발
  Sources/View/Notification/NotificationTableViewCell.swift
Labels: 기능 추가

#28 🔀 :: (#8) MapView UI 및 기본적인 개발 완료
  Podfile
  Podfile.lock
  Sources/Extension/CLLocationManager.swift
  Sources/Extension/MKMapView.swift
  Sources/Model/Brand.swift
  Sources/View/Map/Annotation/StoreAnnotation.swift
  Sources/View/Map/Annotation/StoreMarkerView.swift
  Sources/View/Map/MapViewController.swift
  Supporting Files/Info.plist
Labels: 기능 추가

#33 🔀 :: (#23) 알림 페이지 UI구현
  Sources/Extension/NavigationViewController.swift
  Sources/Extension/ViewController.swift
  Sources/View/Map/MapViewController.swift
  Sources/View/Notification/NotificationViewController.swift
Labels: 기능 추가

#37 🔀 :: (#35) Floating Panel 내용 UI
  Sources/View/Map/MapViewController.swift
  Sources/View/Map/StoreDetailFloatingPanelController.swift
Labels: 기능 추가

#39 ProductTableViewCell 변경
  Sources/View/Reuseable/ProductTableViewCell.swift
Labels: Chore

#40 🔀 :: (#36) ViewModel 생성 및 연결
  Sources/View/Auth/LoginViewController.swift
  Sources/View/Map/MapViewController.swift
  Sources/View/MyPage/MyPageViewController.swift
  Sources/View/Notification/NotificationViewController.swift
  Sources/View/Product/ProductListViewController.swift
  Sources/ViewModel/Auth/LoginViewModel.swift
  Sources/ViewModel/Map/MapViewModel.swift
  Sources/ViewModel/MyPage/MyPageViewModel.swift
  Sources/ViewModel/Notification/NotificationViewModel.swift
  Sources/ViewModel/Product/ProductListViewModel.swift
  Sources/ViewModel/ViewModel.swift
Labels: Chore
