Repository DSM-SSGP/SSGP-iOS, pull requests merged in 2021-11, with the labels that each got.

#66 🔀 :: (#53) 좋아요 표시한 제품 UI완성
  Sources/View/MyPage/Menu/LikedProductViewController.swift
  Sources/View/MyPage/MyPageViewController.swift
Labels: 기능 추가

#73 🔀 :: (#68) 내 정보 수정 페이지 탭바 숨기기
  Sources/View/MyPage/Menu/EditProfileViewController.swift
Labels: Chore

#75 🔀 :: (#74) 내 정보 수정 페이지 텍스트필드 효과
  Sources/Extension/UITextField.swift
  Sources/View/MyPage/Menu/EditProfileViewController.swift
Labels: 기능 추가

#83 🔀 :: (#78) Moya Setting
  .swiftlint.yml
  Podfile
  Podfile.lock
  Sources/Model/Networking/SSGPAPI.swift
  Supporting Files/Info.plist
Labels: 기능 추가

#87 🔀 :: (#86) 맵 API 연동
  Sources/Model/CSStoreModel.swift
  Sources/Model/Networking/SSGPAPI.swift
  Sources/View/Map/Annotation/StoreAnnotation.swift
  Sources/View/Map/Annotation/StoreMarkerView.swift
  Sources/View/Map/MapViewController.swift
  Sources/View/Map/StoreDetailFloatingPanelController.swift
  Sources/ViewModel/Map/MapViewModel.swift
Labels: 기능 추가

#88 🔀 :: (#85) 앱 플로우 정의
  Sources/AppDelegate.swift
  Sources/Model/Networking/SSGPAPI.swift
  Sources/Model/TokenModel.swift
  Sources/View/Auth/LoginViewController.swift
Labels: 기능 추가

#92 🔀 :: (#91) 주변 편의점 로드 플로우 개선
  Sources/View/Map/MapViewController.swift
  Sources/ViewModel/Map/MapViewModel.swift
Labels: 리펙토링

#94 🔀 :: (#93) EmptyViewModel
  Sources/Model/Networking/EmptyModel.swift
Labels: 기능 추가
